### ISSUE TITLE
Auto remove previously posted comments

### ISSUE THREAD

**Issue by grziwok** [krzysztof-miemiec/lemmy#20]
That would be great if Lemmy automatically removes his previous comments when new comment appears. That way PR page would be up to date with current status.

**Comment by krzysztof-miemiec** [comment]
Good idea! I will create three policies for that:
- always remove
- never remove (default - current implementation)
- remove if Lemmy is the last commenter

**Comment by grziwok** [comment]
Sounds great!

**Comment by krzysztof-miemiec** [comment]
@grziwok check out the new 0.1.0 build and  `"removalPolicy": "always"|"never"|"onlyLastComment"` option in `"githubComment"` task 😉

**Comment by grziwok** [comment]
@krzysztof-miemiec I just checked it and it works perfectly, thank you :)
Just a small suggestion, I think it's worth to add this info in documentation.

**Comment by krzysztof-miemiec** [comment]
Will do!
